fragment ServiceParts on Service {
  active
  name
  permalink
  title
  description
  frame_url
  services_tagline
  tags {
    __typename
    name
  }
  order
}

fragment Case_studyParts on Case_study {
  title
  description
  cover_image
  illustration
  color
  category
  services {
    __typename
    name
    timeline
    tags {
      __typename
      name
    }
  }
  testimonial
  cite
  icon
  tags {
    __typename
    name
  }
  size
  aspect
  visible
  solutions {
    __typename
    title
    description
    media
  }
}
