fragment ServiceParts on Service {
  active
  name
  title
  description
  services_tagline
  permalink
  order
  tags {
    __typename
    name
  }
  hero_partial
}

fragment Case_studyParts on Case_study {
  title
  description
  hero_image
  category
  services {
    __typename
    name
    tags {
      __typename
      name
    }
  }
  testimonial
  cite
  icon
  color
  tags {
    __typename
    name
  }
  size
  aspect
  visible
}
