- name: UI Design
  category: product design
  tags:
    - name: figma
    - name: adobe
    - name: sketch
    - name: design systems
- name: Prototying
  category: product design
  tags:
    - name: adobe xd
    - name: design sprint
    - name: user testing
    - name: figma
- name: Web Development
  category: product design
  tags:
    - name: html
    - name: css
    - name: javascript
    - name: webflow
    - name: wordpress
